name: prose-art-gen
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pip>=23
  - pip:
      - fastapi
      - uvicorn[standard]
      - python-dotenv
      - openai
      - langchain-openai
      - langgraph
      - judgeval
      - pinecone
      - sentence-transformers
      - torch           # CPU wheel; install your CUDA/MPS wheel first if you need GPU
      - pillow
      - requests